version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-cdc
    environment:
      - node.name=es-single-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=U9O9Zb7vZ20LTZdOz2vX
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:U9O9Zb7vZ20LTZdOz2vX http://localhost:9200/_cluster/health?pretty | grep -q '\"status\"\\s*:\\s*\"\\(green\\|yellow\\)\"'"]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 180s

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-setup
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: >
      bash -c '
        echo "Waiting for Elasticsearch availability";
        until curl -s -u elastic:U9O9Zb7vZ20LTZdOz2vX http://elasticsearch:9200 | grep -q "cluster_name"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u elastic:U9O9Zb7vZ20LTZdOz2vX -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"U9O9Zb7vZ20LTZdOz2vX\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana-cdc
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=U9O9Zb7vZ20LTZdOz2vX
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - XPACK_SECURITY_ENCRYPTIONKEY=somerandomstringforkibanaencryption32chars
      - XPACK_REPORTING_ENCRYPTIONKEY=anotherrandomstringforreporting32chars
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=yetanotherrandomstringforsavedobjects32
    ports:
      - "5601:5601"
    depends_on:
      setup:
        condition: service_completed_successfully
    restart: on-failure

volumes:
  esdata:
    driver: local